---
- hosts: XR
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
  - name: get IOS-XR running configuration
    cisco.iosxr.iosxr_facts:
    register: iosxr_data
  - debug:
        var: iosxr_data  # Muestra la salida de la tarea "iosxr_facts"

  - name: Apply the provided configuration
    cisco.iosxr.iosxr_hostname:
    config:
      hostname: XR-ANSIBLE
    state: merged
    
